stages:
- sast
- deploy
- test

sonarqube-check:
  stage: sast
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint:
    - ''
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: '0'
  cache:
    key: "${CI_JOB_NAME}"
    paths:
    - ".sonar/cache"
  script:
  - sonar-scanner
  allow_failure: true
  only:
  - dev
  tags:
  - vmogroup

include:
- template: Security/Secret-Detection.gitlab-ci.yml
secret_detection:
  tags:
    - vmogroup

deploy_dev:
  stage: deploy
  script:
    - export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v18.12.0/bin"
    - cd /home/ubuntu/webadmin
    - git reset --hard
    - git pull
    - yarn install
    - yarn build
  only:
    - dev
  tags:
    - c11_klaytn22184_webadmin

deploy_uat:
  stage: deploy
  script:
    - export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v18.12.0/bin"
    - cd /home/ubuntu/webadmin
    - git reset --hard
    - git pull
    - yarn install
    - yarn build
  only:
    - staging
  tags:
    - c11_klaytn22184_webadmin_uat